### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vladimmi** [kree-nickm/ninjaripper-blender-import#1]
Happens at:
https://github.com/kree-nickm/ninjaripper-blender-import/blob/bdb167986d403856ab8748e1870b8a02d889921c/RipMesh.py#L34

With some rip files `normals` can remain `None` because it's not present in file.

It can be more a sort of bug in ninjaripper dump, though, because resulting objects from that dump are damaged even with other plugins in older Blender...

**Comment by hYdos** [comment]
I have a fix for this, if its still an issue let me know and ill upload it as a fork

**Comment by vladimmi** [comment]
Well, I didn't use Ninja Ripper recently and have no idea of current state of Blender plugins for it... But would be great to have it just in case, for sure.

**Comment by mwilmsm** [comment]
I just had this issue as well, attempting to rip from Dragon's Dogma using Ninja Ripper 1.7.1's D3D9 wrapper:

```
Python: Traceback (most recent call last):
  File "C:\Users\(username here)\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\ninjaripper-blender-import-main\__init__.py", line 90, in execute
    mesh.loadRip()
  File "C:\Users\(username here)\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\ninjaripper-blender-import-main\RipMesh.py", line 34, in loadRip
    vtx.normal = mathutils.Vector(vert[normals['label']][0:3]) # I've seen rips with 4-dimensional normals, no idea what the deal is with that
TypeError: 'NoneType' object is not subscriptable

location: <unknown location>:-1
```

Notably this was after successfully importing several folders the exact same way, so I'm not sure I'll be able to isolate the object causing the issue.

**Comment by umustbeloggedintododat** [comment]
> I have a fix for this, if its still an issue let me know and ill upload it as a fork

please!

**Comment by TTHDaniel** [comment]
> I have a fix for this, if its still an issue let me know and ill upload it as a fork

Please upload it

**Comment by ArazSeyfinezhad** [comment]
I was trying to use this addon for .rip files created by NinjaRipper 1.7.1 on Need for Speed Carbon, some files import however most produce this exact error.
