### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by ghost** [kree-nickm/ninjaripper-blender-import#8]
Dunno if this is still active but I only get an error

```
Python: Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ninjaripper-blender-import-main\__init__.py", line 65, in execute
    rip.parse(xyzOrder=self.xyzOrder, uvOrder=self.uvOrder, scale=self.scale, keep2D=self.keep2D, keepUntextured=self.keepUntextured)
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ninjaripper-blender-import-main\RipFile.py", line 95, in parse
    if data[i] > self.pMax[i]:
IndexError: list index out of range

```

**Comment by kree-nickm** [comment]
Apparently recent versions of NinjaRipper changed the way its ripped files are saved. I made this script for NinjaRipper 1.7.1 and hopefully it still works with that version. Someone submitted a pull request that apparently fixes at least one issue with the new NinjaRipper files, but I have no idea. You could try his version: [https://github.com/derivator/ninjaripper-blender-import](https://github.com/derivator/ninjaripper-blender-import)

**Comment by ghost** [comment]
Didn't work either, same error, am I getting the 2 mixed up because my ninjaripper is 1.7.1

**Comment by ghost** [comment]
If it helps, I'm using blender 3.6.1

**Comment by TeridaxXD001** [comment]
Worked a couple weeks ago and now suddenly doesn't. Baffling. Same version of Ninja Ripper and Blender.
